#FROM artifactory.axisb.com/axisomnibanking-dev-docker-local/openjdk/openjdk-17:17.1.0
#FROM adoptopenjdk/openjdk17:alpine-jre
#USER root
#RUN chmod 777 /mnt/
#COPY ./target/request.statement-0.0.1-SNAPSHOT.jar /request.statement-0.0.1-SNAPSHOT.jar
#HEALTHCHECK --interval=300s --timeout=10s --start-period=30s CMD curl --fail http://localhost:8086/actuator/health || exit 1
#CMD ["java","-jar","/request.statement-0.0.1-SNAPSHOT.jar","--spring.config.location=/etc/config/application.properties"]